apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: dex-addon
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "DEX OIDC Identity Provider for KubeVela SSO"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          metadata: {
            name:      "dex"
            namespace: "vela-system"
            labels: {
              "app": "dex"
            }
          }
          spec: {
            replicas: 1
            selector: {
              matchLabels: {
                "app": "dex"
              }
            }
            template: {
              metadata: {
                labels: {
                  "app": "dex"
                }
              }
              spec: {
                containers: [{
                  name:  "dex"
                  image: "quay.io/dexidp/dex:v2.36.0"
                  ports: [{
                    containerPort: 5556
                    name:          "http"
                  }]
                  args: [
                    "/usr/local/bin/dex",
                    "serve",
                    "/etc/dex/cfg/config.yaml"
                  ]
                  volumeMounts: [{
                    name:      "config"
                    mountPath: "/etc/dex/cfg"
                  }]
                  env: [
                    {
                      name:  "DEX_OVERWRITE_INTEGRATION_CALLBACKS"
                      value: "true"
                    }
                  ]
                }]
                volumes: [{
                  name: "config"
                  configMap: {
                    name: "dex-config"
                  }
                }]
              }
            }
          }
        }